# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test macOS 14

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
